# Generated by Django 3.2.8 on 2021-10-20 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=150)),
                ('blog_date', models.DateField(auto_now_add=True)),
                ('blog_text', models.TextField(blank=True)),
                ('blog_image', models.ImageField(upload_to='photos/%Y/%m/%d/')),
            ],
        ),
    ]
